mqtt:
    broker: tcp://mqtt.eclipseprojects.io:1883
security:
    jwt:
        token:
            secret-key: 53cr37
            expire-length: 3600000
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/water_monitor?useTimezone=true&serverTimezone=UTC
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
            show-sql: false
    output:
        ansi:
            enabled: ALWAYS